package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/spf13/cobra"
)

var describeCmd = &cobra.Command{
	Use:   "describe",
	Short: "Print app structure as JSON (useful as AI context)",
	RunE:  runDescribe,
}

var describeMD bool

func init() {
	describeCmd.Flags().BoolVar(&describeMD, "md", false, "Also write FORGE.md with app description")
	rootCmd.AddCommand(describeCmd)
}

type appDescription struct {
	App         string          `json:"app"`
	GeneratedAt string          `json:"generated_at"`
	Routes      json.RawMessage `json:"routes"`
	Controllers []string        `json:"controllers"`
	Models      []string        `json:"models"`
	Views       []string        `json:"views"`
	Migrations  []migInfo       `json:"migrations"`
}

type migInfo struct {
	Version string `json:"version"`
	Name    string `json:"name"`
}

func runDescribe(cmd *cobra.Command, args []string) error {
	desc := appDescription{
		App:         appName(),
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
	}

	desc.Controllers = scanDir("app/controllers", "_controller.go", "")
	desc.Models = scanDir("app/models", ".go", "")
	desc.Views = scanViews()
	desc.Migrations = scanMigrations()
	desc.Routes = fetchRoutes()

	out, err := json.MarshalIndent(desc, "", "  ")
	if err != nil {
		return err
	}
	fmt.Println(string(out))

	if describeMD {
		if err := writeForgeMD(desc); err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not write FORGE.md: %v\n", err)
		} else {
			fmt.Fprintln(os.Stderr, "=> wrote FORGE.md")
		}
	}

	return nil
}

// appName reads the module name from go.mod.
func appName() string {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return "unknown"
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				// return last path segment: "github.com/myapp" → "myapp"
				seg := strings.Split(parts[1], "/")
				return seg[len(seg)-1]
			}
		}
	}
	return "unknown"
}

// scanDir lists files in dir, stripping the given suffix and optional prefix.
func scanDir(dir, stripSuffix, stripPrefix string) []string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), stripSuffix) {
			continue
		}
		name := strings.TrimSuffix(e.Name(), stripSuffix)
		name = strings.TrimPrefix(name, stripPrefix)
		names = append(names, name)
	}
	return names
}

// scanViews walks app/views/ and returns all .templ files relative to app/views/.
func scanViews() []string {
	var views []string
	_ = filepath.WalkDir("app/views", func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		if strings.HasSuffix(path, ".templ") {
			rel := strings.TrimPrefix(path, "app/views/")
			rel = strings.TrimSuffix(rel, ".templ")
			views = append(views, rel)
		}
		return nil
	})
	return views
}

// scanMigrations lists migration files from db/migrations/.
func scanMigrations() []migInfo {
	entries, err := os.ReadDir("db/migrations")
	if err != nil {
		return nil
	}
	var migs []migInfo
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".sql") {
			continue
		}
		base := strings.TrimSuffix(e.Name(), ".sql")
		parts := strings.SplitN(base, "_", 2)
		m := migInfo{Version: parts[0]}
		if len(parts) == 2 {
			m.Name = parts[1]
		}
		migs = append(migs, m)
	}
	return migs
}

// fetchRoutes runs the app with FORGE_CMD=routes:json and captures the output.
// Returns nil JSON if the app can't be run (e.g. not compiled yet).
func fetchRoutes() json.RawMessage {
	var buf bytes.Buffer
	c := exec.Command("go", "run", ".")
	c.Env = append(os.Environ(), "FORGE_CMD=routes:json")
	c.Stdout = &buf
	c.Stderr = nil // suppress build/startup noise

	if err := c.Run(); err != nil {
		return json.RawMessage("null")
	}

	raw := bytes.TrimSpace(buf.Bytes())
	if !json.Valid(raw) {
		return json.RawMessage("null")
	}
	return json.RawMessage(raw)
}

// --- FORGE.md generation ---

var forgeMDTmpl = "# {{.App}} — Forge app\n" +
	"\n" +
	"> Generated by `forge describe` on {{.GeneratedAt}}\n" +
	"> Feed this file to an AI agent for full app context.\n" +
	"\n" +
	"## Routes\n" +
	"{{- if .Routes}}\n" +
	"| Method | Path | Controller | Action |\n" +
	"|--------|------|------------|--------|\n" +
	"{{- range .Routes}}\n" +
	"| {{.Method}} | {{.Path}} | {{.Controller}} | {{.Action}} |\n" +
	"{{- end}}\n" +
	"{{- else}}\n" +
	"_Run `forge describe` with the app compiled to include routes._\n" +
	"{{- end}}\n" +
	"\n" +
	"## Controllers\n" +
	"{{- range .Controllers}}\n" +
	"- {{.}}\n" +
	"{{- else}}\n" +
	"_none_\n" +
	"{{- end}}\n" +
	"\n" +
	"## Models\n" +
	"{{- range .Models}}\n" +
	"- {{.}}\n" +
	"{{- else}}\n" +
	"_none_\n" +
	"{{- end}}\n" +
	"\n" +
	"## Views\n" +
	"{{- range .Views}}\n" +
	"- {{.}}\n" +
	"{{- else}}\n" +
	"_none_\n" +
	"{{- end}}\n" +
	"\n" +
	"## Migrations\n" +
	"{{- range .Migrations}}\n" +
	"- `{{.Version}}` {{.Name}}\n" +
	"{{- else}}\n" +
	"_none_\n" +
	"{{- end}}\n"

type forgeMDData struct {
	App         string
	GeneratedAt string
	Routes      []routeInfo
	Controllers []string
	Models      []string
	Views       []string
	Migrations  []migInfo
}

type routeInfo struct {
	Method     string `json:"method"`
	Path       string `json:"path"`
	Controller string `json:"controller"`
	Action     string `json:"action"`
}

func writeForgeMD(desc appDescription) error {
	data := forgeMDData{
		App:         desc.App,
		GeneratedAt: desc.GeneratedAt,
		Controllers: desc.Controllers,
		Models:      desc.Models,
		Views:       desc.Views,
		Migrations:  desc.Migrations,
	}

	// Try to parse routes JSON into typed slice for the template.
	if desc.Routes != nil && string(desc.Routes) != "null" {
		_ = json.Unmarshal(desc.Routes, &data.Routes)
	}

	tmpl, err := template.New("forge.md").Parse(forgeMDTmpl)
	if err != nil {
		return err
	}

	f, err := os.Create("FORGE.md")
	if err != nil {
		return err
	}
	defer f.Close()

	return tmpl.Execute(f, data)
}
